<?php

namespace AppBundle\Repository;

/**
 * GuestRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
