<?php

namespace AppBundle\Repository;

/**
 * GuestRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestRoomRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRoomCount($type)
    {
        $em = $this->getEntityManager();

        $queryBuilder = $em->createQueryBuilder()
            ->select('sum(g.number)')
            ->from('AppBundle\Entity\GuestRoom', 'g')
            ->where('g.type = :type');
        $queryBuilder->setParameter('type',$type);
        return $queryBuilder->getQuery()->getSingleScalarResult();
    }
}
