language: php
php:
- '5.6'
- '7.0'
install:
- cd code
- composer install
- php bin/console assetic:dump
- php bin/console cache:clear
- php bin/console server:start
script:
- ./vendor/bin/codecept run
before_install:
- openssl aes-256-cbc -K $encrypted_a2051fc99353_key -iv $encrypted_a2051fc99353_iv
  -in build/sshkeys/travis_key.rsa.enc -out build/sshkeys/travis_key.rsa -d
after_success:
- cd ../
- chmod 600 build/sshkeys/travis_key.rsa
- tar -czf site.tar.gz code/*
- 'scp -i build/sshkeys/travis_key.rsa site.tar.gz ubuntu@melanieandcolin.uk:'
- ssh -i build/sshkeys/travis_key.rsa ubuntu@melanieandcolin.uk "tar -xzf site.tar.gz -C /var/www/melanieandcolin.co.uk"
addons:
  ssh_known_hosts: melanieandcolin.uk
