language: php
php:
  - '5.6'
  - '7.0'
install:
  - cd code
  - composer install
  - ls
  - ls bin/
  - ls app/
  - php bin/console assetic:dump
  - php bin/console cache:clear
  - alias codecept='./vendor/bin/codecept'
  - php bin/console server:run
script: code/vendor/bin/codecept run
