language: php
php:
- '7.0'
services:
- mysql
install:
- cd code
- composer install
- php bin/console assetic:dump
- php bin/console cache:clear
- php bin/console server:start
script:
- ./vendor/bin/codecept run
before_install:
- openssl aes-256-cbc -K $encrypted_a2051fc99353_key -iv $encrypted_a2051fc99353_iv
  -in build/sshkeys/travis_key.rsa.enc -out build/sshkeys/travis_key.rsa -d
- mysql -u root -e 'create database weddingsite character set utf8mb4;'
after_success:
- php bin/console server:stop
- cd ../
- chmod 600 build/sshkeys/travis_key.rsa
- build/deploy.sh
- exit
addons:
  ssh_known_hosts: melanieandcolin.uk
