language: php
php:
  - '5.6'
  - '7.0'
install:
  - cd code
  - composer install
  - php bin/console assetic:dump
  - php bin/console cache:clear
  - php bin/console server:start
script:
  - ls ./vendor/bin/
  - ./vendor/bin/codecept run
