language: php
php:
- '7.0'
services:
- mysql
env:
  - DATABASE_HOST="localhost" DATABASE_NAME="weddingsite" DATABASE_USER="test" DATABASE_PASSWORD="tests"
install:
- cd code
- composer install
- php bin/console assetic:dump
- php bin/console cache:clear
- php bin/console doctrine:migrations:migrate --no-interaction
- php bin/console server:start
script:
- ./vendor/bin/codecept run
before_deploy:
- php bin/console server:stop
before_install:
- openssl aes-256-cbc -K $encrypted_a2051fc99353_key -iv $encrypted_a2051fc99353_iv
  -in build/sshkeys/travis_key.rsa.enc -out build/sshkeys/travis_key.rsa -d
- mysql -u root -e 'create database weddingsite character set utf8mb4;'
- mysql -u root -e 'grant all privileges on weddingsite.* to "test"@"localhost" identified by "tests"; flush privileges;'
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIJSEMFIZUI6YICEA
  secret_access_key:
    secure: Uvdwhl/sL9ThQ241hnR/RXZJC7nEUPHsptxaBh60rlKsvWqdGZqozyeebewRBcB6nJlcq37xHtBs+bi3ApIFCKDuJ/O1oim8B4SyV6nMhdqoapo/f/RWzSzyrGstK56Ev24GDK8klOZ/fiFg5kiL60dGRAvm9OR+26TrhAsannuJAjTjv7Evh9uDljC83QDaSHDViX3oo/IZU88xRN0MnhLsTYFgySGVlVrpXsxFNRGbOrMps01Wc5FfHb6nlnbD3Zs4Kj58H2gmIAVCzswCx+pGuK3TnJ1fXVyqZ85Y9Psb5hnO7+3juoaSiTXlk+a/hF8u2lZR3TLSZjFMm74IBtwYHFhag5hja/TGgjlMjgZXVR3u86AZCmaBS2EK5/HgZVjXHd3USgp+QGE+d+4JjCKrb0LGBChs7xk85C5/nQnDQQuibM3E4Me1yavMyCXVbGpD4HCo6tC+3M+cCnAt/tutgyObg01Ugv/R5bdYJCA3v3aj7oLjL2pkGRoQRTlq/HVWOYO/03FVyZscVU0UANQQDk3KKiKwWMQ/wLm4XNufo+1C2UVjMTUqbTUX2xn3wADW7JNsNLjbMvNQJqjouaAaNJrvtV2lvFFVLNGXkjzGR/oeO+2ob8vhIKxsJseo5dTMVlV+qmxuOHi5SiVbjAFOr9M0/pisNn1zFi+YZTg=
  region: eu-west-2
  app: melanieandcolin
  env: Custom-env
  bucket_name: melanieandcolin
  on:
    repo: colsil/melanieandcolin.co.uk

